apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ms-login
  namespace: '780675609467'
  selfLink: /apis/serving.knative.dev/v1/namespaces/780675609467/services/ms-login
  uid: 21a6d27a-e73d-457c-a6c1-13fad9dad36a
  resourceVersion: AAZHhvbRvPc
  generation: 7
  creationTimestamp: '2026-01-02T15:53:07.833306Z'
  labels:
    commit-sha: 4b0a0ebdd4d475a0b212ecc80ffbb65dd9e85a38
    gcb-build-id: 6c3c50e8-af4b-4970-b9e5-a603880d3193
    gcb-trigger-id: a6e1ff98-7a33-4034-80dd-4a3e99615a16
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
    cloud.googleapis.com/location: us-central1
  annotations:
    serving.knative.dev/creator: dpcamargo@gmail.com
    serving.knative.dev/lastModifier: dpcamargo@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: 152e753d-52f1-4d80-b62f-41ecd0c3683d
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/maxScale: '1'
    run.googleapis.com/urls: '["https://ms-login-780675609467.us-central1.run.app","https://ms-login-p72ngdpwvq-uc.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: d7e610a2-c900-40e1-acd3-28b6b5df97af
        commit-sha: 4b0a0ebdd4d475a0b212ecc80ffbb65dd9e85a38
        gcb-build-id: 6c3c50e8-af4b-4970-b9e5-a603880d3193
        gcb-trigger-id: a6e1ff98-7a33-4034-80dd-4a3e99615a16
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 780675609467-compute@developer.gserviceaccount.com
      containers:
        - name: placeholder-1
          image: us-central1-docker.pkg.dev/fiap-474820/cloud-run-source-deploy/ms-login/ms-login:4b0a0ebdd4d475a0b212ecc80ffbb65dd9e85a38
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: LOGIN_PORT
              value: '8080'
            - name: USUARIO_HOST
              value: https://ms-usuario-780675609467.us-central1.run.app/ms-usuario/v1/
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: JWT_ACCESS_TOKEN
            - name: JWT_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: JWT_REFRESH_TOKEN
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              path: /ms-login/ping
              port: 8080
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true
status:
  observedGeneration: 7
  conditions:
    - type: Ready
      status: 'True'
      lastTransitionTime: '2026-01-04T02:47:32.394231Z'
    - type: ConfigurationsReady
      status: 'True'
      lastTransitionTime: '2026-01-04T02:47:30.662470Z'
    - type: RoutesReady
      status: 'True'
      lastTransitionTime: '2026-01-04T02:47:32.349712Z'
  latestReadyRevisionName: ms-login-00006-74c
  latestCreatedRevisionName: ms-login-00006-74c
  traffic:
    - revisionName: ms-login-00006-74c
      percent: 100
      latestRevision: true
  url: https://ms-login-p72ngdpwvq-uc.a.run.app
  address:
    url: https://ms-login-p72ngdpwvq-uc.a.run.app
